import urllib
f = open('ardu.ino', 'w')
f.write(urllib.urlopen('https://github.com/ikscoder/WorldSkills/blob/master/ardu/ardu.ino').read())
f = open('Generator.py', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/Generator/Generator/Generator.py').read())
f = open('AllEntities.twx', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/AllEntities.twx').read())
f = open('MainWindow.xaml.cs', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/LocalServer/LocalServer/MainWindow.xaml.cs').read())
f = open('MainWindow.xaml', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/LocalServer/LocalServer/MainWindow.xaml').read())
#graphon
f = open('button.xaml', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/LocalServer/LocalServer/button.xaml').read())
f = open('scroll.xaml', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/LocalServer/LocalServer/scroll.xaml').read())
f = open('textbox.xaml', 'w')
f.write(urllib.urlopen('https://raw.githubusercontent.com/ikscoder/WorldSkills/master/LocalServer/LocalServer/textbox.xaml').read())